import TopHeader from '../components/top_header';
import Header from '../components/header';
import PopMobile from '../components/pop_mobile';
import Footer from '../components/footer';
import CopyRight from '../components/copyRight';
import Scripts from '../components/scripts';
import "./globals.css"; // Global CSS imports

export const metadata = {
  title: "Nexus Filehub",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/Images/logo/favicon.png",
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'http://localhost:3000/',
    siteName: 'Nexus Filehub',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="theme-style-mode" content="1" />
        <link rel="shortcut icon" type="image/x-icon" href="/assets/Images/logo/favicon.png" />
      </head>
      <body>
        {/* CSS Imports in globals.css or component-level */}

        {/* Layout Components */}
        <TopHeader />
        <Header />
        <PopMobile />
        <main>{children}</main>
        <Footer />
        <CopyRight />
        <Scripts />
      </body>
    </html>
  );
}
